Vpolazava/kin 11 details screen UI/develope
niewyspana/KinoRepo pull request #4
Opened 2024-08-26 10:55 UTC by niewyspana

added Coordinator

2024-08-26 12:31 UTC, Darya-Astapava requested changes

2024-08-26 12:31 UTC, Darya-Astapava commented on Kino/MainScreen/View/Coordinators/AppCoordinator.swift
> +    var children: [any CoordinatorProtocol] = []
For what do you use any here?

2024-08-26 12:31 UTC, Darya-Astapava commented on Kino/MainScreen/View/Coordinators/AppCoordinator.swift
> +        print("AppCoordinator started")
remove debug print

2024-08-26 12:31 UTC, Darya-Astapava commented on Kino/MainScreen/View/Coordinators/HomeScreenCoordinator.swift
> +    internal var navigationController: UINavigationController
Internal is default access level, you don't need to make it explicit

2024-08-26 12:31 UTC, Darya-Astapava commented on Kino/MainScreen/View/Coordinators/HomeScreenCoordinator.swift
> +        let ticket = TicketsViewController(nibName: "TicketsViewController", bundle: nil)
use full names like ticketViewController, because "ticket" is more like a model, not a viewController instance

2024-08-26 12:31 UTC, Darya-Astapava commented on Kino/MainScreen/View/Coordinators/HomeScreenCoordinator.swift
> +        let fav = FavouritesViewController(nibName: "FavouritesViewController", bundle: nil)
the same

2024-08-26 12:31 UTC, Darya-Astapava commented on Kino/MainScreen/View/Coordinators/HomeScreenCoordinator.swift
> +}
How I can see in Figma, the first screen should have one or two more navigation methods for see more buttons

2024-08-26 12:31 UTC, Darya-Astapava commented on Kino/MainScreen/ViewModel/MainScreenViewModel.swift
> +    var coordinator: HomeScreenCoordinator!
Don't use force unwrap!

2024-08-26 14:40 UTC, niewyspana commented on Kino/MainScreen/View/Coordinators/AppCoordinator.swift
> +    var children: [any CoordinatorProtocol] = []
done

2024-08-26 14:40 UTC, niewyspana commented on Kino/MainScreen/View/Coordinators/AppCoordinator.swift
> +        print("AppCoordinator started")
done

2024-08-26 14:42 UTC, niewyspana commented on Kino/MainScreen/View/Coordinators/HomeScreenCoordinator.swift
> +        let ticket = TicketsViewController(nibName: "TicketsViewController", bundle: nil)
done

2024-08-26 14:43 UTC, niewyspana commented on Kino/MainScreen/View/Coordinators/HomeScreenCoordinator.swift
> +        let fav = FavouritesViewController(nibName: "FavouritesViewController", bundle: nil)
done

2024-08-26 14:47 UTC, niewyspana commented on Kino/MainScreen/ViewModel/MainScreenViewModel.swift
> +    var coordinator: HomeScreenCoordinator!
done

2024-08-26 16:22 UTC, niewyspana commented on Kino/MainScreen/View/Coordinators/HomeScreenCoordinator.swift
> +}
done

2024-08-29 11:25 UTC, Darya-Astapava approved these changes
with one comment

2024-08-29 11:25 UTC, Darya-Astapava commented on Kino/MainScreen/ViewModel/MainScreenViewModel.swift
> +        if let coordinator = coordinator {
It would be better to use guard here

2024-09-06 15:30 UTC, niewyspana commented on Kino/MainScreen/ViewModel/MainScreenViewModel.swift
> +        if let coordinator = coordinator {
done

2024-09-06 15:31 UTC, merged